# Generated by Django 5.0.6 on 2024-07-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('department_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'modules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'type_documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dependencies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.CharField(max_length=250)),
                ('p_city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.cities')),
                ('p_department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.departments')),
                ('p_doc_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.typedocuments')),
            ],
            options={
                'db_table': 'Person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=250)),
                ('a_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.person')),
                ('a_rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.role')),
            ],
            options={
                'db_table': 'auth',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subdependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('acronym', models.CharField(blank=True, max_length=5, null=True)),
                ('dependencie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.dependencies')),
            ],
            options={
                'db_table': 'subdependencies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ug_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.auth')),
                ('ug_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.group')),
            ],
            options={
                'db_table': 'user_groups',
                'managed': True,
                'unique_together': {('ug_auth', 'ug_group')},
            },
        ),
        migrations.AddField(
            model_name='auth',
            name='a_group',
            field=models.ManyToManyField(through='general.UserGroup', to='general.group'),
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.group')),
                ('gr_role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.role')),
            ],
            options={
                'db_table': 'group_roles',
                'managed': True,
                'unique_together': {('gr_group', 'gr_role')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_permission', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.permission')),
                ('rp_role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='general.role')),
            ],
            options={
                'db_table': 'role_permissions',
                'managed': True,
                'unique_together': {('rp_role', 'rp_permission')},
            },
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.auth')),
                ('um_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.module')),
            ],
            options={
                'db_table': 'user_modules',
                'managed': True,
                'unique_together': {('um_auth', 'um_module')},
            },
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ump_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.auth')),
                ('ump_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.module')),
                ('ump_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.permission')),
            ],
            options={
                'db_table': 'user_module_permissions',
                'managed': True,
                'unique_together': {('ump_auth', 'ump_module', 'ump_permission')},
            },
        ),
    ]
